"""
Create and validate the MIRA Milvus collection.

The live MIRA.ai model produces 1024-dimensional embeddings.
The Milvus collection must use the same dimension.

Run from backend:

    python create_milvus_collection.py
"""

from __future__ import annotations

from pymilvus import (
    Collection,
    CollectionSchema,
    DataType,
    FieldSchema,
    connections,
    utility,
)

from app.core.config import settings


COLLECTION_NAME = settings.milvus_collection
MILVUS_HOST = settings.milvus_host
MILVUS_PORT = settings.milvus_port

# AshIndian/Mira.ai produces 1024-dimensional vectors.
EMBEDDING_DIM = 1024


def _existing_embedding_dimension(
    collection: Collection,
) -> int | None:
    """Read the dimension of an existing embedding field."""
    for field in collection.schema.fields:
        if field.name != "embedding":
            continue

        params = getattr(field, "params", {}) or {}

        dimension = params.get("dim")
        if dimension is not None:
            return int(dimension)

    return None


def create_collection() -> int:
    print(
        f"Connecting to Milvus at "
        f"{MILVUS_HOST}:{MILVUS_PORT}..."
    )

    connections.connect(
        alias="default",
        host=MILVUS_HOST,
        port=MILVUS_PORT,
    )

    print(f"Collection name: {COLLECTION_NAME}")
    print(f"Required vector dimension: {EMBEDDING_DIM}")

    if utility.has_collection(COLLECTION_NAME):
        existing = Collection(COLLECTION_NAME)
        existing_dimension = _existing_embedding_dimension(
            existing
        )

        print("Collection already exists.")
        print(
            f"Existing vector dimension: "
            f"{existing_dimension}"
        )

        if existing_dimension != EMBEDDING_DIM:
            print()
            print("DIMENSION MISMATCH")
            print(
                f"The existing collection uses "
                f"{existing_dimension} dimensions."
            )
            print(
                f"The MIRA.ai model uses "
                f"{EMBEDDING_DIM} dimensions."
            )
            print()
            print(
                "Do not insert vectors yet. The collection "
                "must be rebuilt before the final upload."
            )
            return 1

        print(
            "Collection dimension is compatible with "
            "AshIndian/Mira.ai."
        )
        print("No collection changes were made.")
        return 0

    fields = [
        FieldSchema(
            name="id",
            dtype=DataType.INT64,
            is_primary=True,
            auto_id=False,
        ),
        FieldSchema(
            name="embedding",
            dtype=DataType.FLOAT_VECTOR,
            dim=EMBEDDING_DIM,
        ),
        FieldSchema(
            name="cpse",
            dtype=DataType.VARCHAR,
            max_length=100,
        ),
        FieldSchema(
            name="category",
            dtype=DataType.VARCHAR,
            max_length=100,
        ),
    ]

    schema = CollectionSchema(
        fields,
        description=(
            "MIRA material description embeddings "
            "generated by AshIndian/Mira.ai"
        ),
    )

    collection = Collection(
        name=COLLECTION_NAME,
        schema=schema,
    )

    index_params = {
        "index_type": "IVF_FLAT",
        "metric_type": "COSINE",
        "params": {
            "nlist": 128,
        },
    }

    collection.create_index(
        field_name="embedding",
        index_params=index_params,
    )

    collection.load()

    print()
    print(
        f"Created collection '{COLLECTION_NAME}' "
        f"with dimension={EMBEDDING_DIM}."
    )
    print("Metric: COSINE")
    print("Index: IVF_FLAT")
    print("Collection loaded successfully.")

    return 0


if __name__ == "__main__":
    raise SystemExit(create_collection())